// <auto-generated />
using CRUDMToM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDMToM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210317133703_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDMToM.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empployees");
                });

            modelBuilder.Entity("CRUDMToM.Models.Employeeskill", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("CRUDMToM.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SkillName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillName = "Communication"
                        },
                        new
                        {
                            Id = 2,
                            SkillName = "Decision-Making"
                        },
                        new
                        {
                            Id = 3,
                            SkillName = "Flexibility"
                        },
                        new
                        {
                            Id = 4,
                            SkillName = "Innovation"
                        },
                        new
                        {
                            Id = 5,
                            SkillName = "Integrity"
                        },
                        new
                        {
                            Id = 6,
                            SkillName = "Leadership"
                        },
                        new
                        {
                            Id = 7,
                            SkillName = "Time Management"
                        },
                        new
                        {
                            Id = 8,
                            SkillName = "Negotiation"
                        });
                });

            modelBuilder.Entity("CRUDMToM.Models.Employeeskill", b =>
                {
                    b.HasOne("CRUDMToM.Models.Employee", "Employees")
                        .WithMany("Employeeskills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDMToM.Models.Skill", "Skills")
                        .WithMany("Employeeskills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CRUDMToM.Models.Employee", b =>
                {
                    b.Navigation("Employeeskills");
                });

            modelBuilder.Entity("CRUDMToM.Models.Skill", b =>
                {
                    b.Navigation("Employeeskills");
                });
#pragma warning restore 612, 618
        }
    }
}
